#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend abdurleone_frontend
	bind *:80
	mode http
	default_backend abdurleone_backend
backend abdurleone_backend
  	balance roundrobin
	server 261719-web-01 34.207.121.60 check
	server 261719-web-02 100.25.164.228 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

#TESTING the HAproxy configutarion file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

#Restart the service
sudo service haproxy restart
