#!/usr/bin/env bash
# while loop script that displays the content of the file /etc/passwd.
# and only display

#  username
#  user id
#  Home directory path for the user

while read -r passwd;
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
