#!/usr/bin/env bash
# while loop script to display Best School 10 times,for the 9th iteration, echo Best School then Hi in new line.

i=0

while [ $i -lt 10 ]
do
	if [ i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done
