#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes.

#   echo hours from 0 to 12
#   echo minutes from 1 to 59

hours=0

while [ $hour -le 12 ]
do
	echo "Hour: $hours"
	minute=1
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		(( minutes++ ))
	done
	(( hours++ ))
done
